### ISSUE TITLE
Updata sf version and QA

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/authentication-bundle#13]
## Goal

Make this bundle up to date with symfony version and QA tools.

**Comment by mathieu-ducrot** [comment]
PR QA Tools https://github.com/smartbooster/authentication-bundle/pull/14/files

**Comment by mathieu-ducrot** [comment]
PR Fidry\AliceDataFixtures + SF4 action naming compatibility https://github.com/smartbooster/authentication-bundle/pull/18/files
