### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by nicolas-bastien** [smartbooster/authentication-bundle#4]
https://github.com/smartbooster/sandbox/issues/2

Implement forgot password system.

**Comment by mathieu-ducrot** [comment]
Find this translation mistake on the forget password screen, maybe we can fix it before closing this issue.

![screenshot-admin site local-2018 05 03-11-05-36](https://user-images.githubusercontent.com/17027450/39568718-6360019e-4ec3-11e8-8ba9-99648a78abfb.png)

Flash message should be : 

> Nous vous avons envoyé un email pour réinitialiser votre mot de passe.

**Edit** : I fixed it in this PR https://github.com/smartbooster/authentication-bundle/pull/7

**Comment by mathieu-ducrot** [comment]
@nicolas-bastien At the moment enter a not found email behave in redirecting to the login screen without flash message. 

We should add it anytime so that nobody can detect if the email exist in the database or not.
